version: "3.8"
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=srisuba
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        ports:
            - 5434:5432
        networks:
            - postgres-db-network
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "teste@teste.com"
            PGADMIN_DEFAULT_PASSWORD: "teste"
        ports:
            - 16533:80
        volumes:
            - ./servers.json:/pgadmin4/servers.json
        networks:
            - postgres-db-network

volumes:
    postgres-db-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data
networks:
    postgres-db-network:
        driver: bridge
